# Generated by Django 4.1.4 on 2022-12-28 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientsApp', '0001_initial'),
        ('authApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='patients',
            field=models.ManyToManyField(null=True, to='patientsApp.patient'),
        ),
    ]
